TDD: Nesting tz_offset should work too
But this test currently fails with

```
        assert dt0 == dt0_2
>       assert dt1 == dt1_2
E       assert FakeDatetime(2016, 1, 1, 14, 54) == FakeDatetime(2016, 1, 1, 13, 54)
```

because the decorator sets TZ_OFFSET to 0 on exit, regardless of what it
was before.